import { Metadata } from "next";

export const metadata: Metadata = {
    title: "About Page",
    description: "Generated by create next app",
};

export default function About() {
    return (
        <div className="flex items-center justify-center min-h-content">
            <h2 className="text-3xl font-bold text-red-200">About Page</h2>
        </div>
    );
}
