import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Contact Page",
    description: "Generated by create next app",
};


export default function Contact() {
    return (
        <div className="flex items-center justify-center min-h-content">
            <h2 className="text-3xl font-bold text-red-200">Contact Page</h2>
        </div>
    );
}
